const constants = {
  ADD_EVENT: "ADD_EVENT",
  REMOVE_EVENT: "REMOVE_EVENT",
  EXPORT_EVENTS: "EXPORT_EVENTS",
  CREATE_USER: "CREATE_USER",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT"
}
export default constants
